title:            Stephen Ripley's blog
tagline:          Software engineering, cooking, and deep thoughts
description:      Describe your website.
canonical: http://stephenripley.com

# Owner/author information
owner:
  name:           Stephen Ripley
  avatar:         avatar.png
  bio:            "Dad, Husband, Software Engineer, Cook, Traveler and Enjoyer of All That is Good"
  email:          sripley@gmail.com
  twitter:        sripley
  github:         sripley
  instagram:      sripley
#  dribbble:       coletownsend
#  disqus:         balzac
  location:       "Oakland, CA"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/San_Francisco
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  enable_coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

comments :
  provider : disqus
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
